name: Mirror Codeberg to GitHub
on:
  schedule:
    - cron: '0 * * * *'  # Runs every 60 minutes
  workflow_dispatch:       # Allows manual triggering
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror Codeberg to GitHub
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan codeberg.org >> ~/.ssh/known_hosts
          git clone --mirror git@codeberg.org:kvl/AdvancedCPP.git
          cd AdvancedCPP.git
          git remote add github git@github.com:kristofvl/AdvancedCPP.git
          git push github --mirror
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
